version: "3.8"

services:
  app:
    image: registry.gitlab.com/(runnername)/(projectname):latest
    ports:
      - '${APP_PORT}:${APP_PORT}'
    working_dir: '/var/www/html'
    environment:
      TZ: '${APP_TIMEZONE}'
    env_file:
      - .env.example
    restart: always
