# syntax=docker/dockerfile:1

ARG GOLANG_VERSION

FROM golang:$GOLANG_VERSION-alpine

WORKDIR /var/www/html

RUN go install github.com/cosmtrek/air@latest

COPY go.mod go.sum ./

RUN go mod download

CMD ["air", "-c", ".air.toml", "serve"]