definitions:
  domain.Admin:
    properties:
      account:
        type: string
      created_at:
        type: string
      id:
        type: string
      password:
        type: string
      updated_at:
        type: string
    type: object
  domain.LoginAndRegisterRequest:
    properties:
      account:
        example: account
        type: string
      password:
        example: password
        type: string
    required:
    - account
    - password
    type: object
  domain.LoginResponse-domain_Admin:
    properties:
      t:
        $ref: '#/definitions/domain.Admin'
      token:
        type: string
    type: object
  domain.LoginResponse-domain_User:
    properties:
      t:
        $ref: '#/definitions/domain.User'
      token:
        type: string
    type: object
  domain.User:
    properties:
      account:
        type: string
      created_at:
        type: string
      id:
        type: string
      password:
        type: string
      updated_at:
        type: string
    type: object
  response.RespnseStr:
    properties:
      code:
        type: integer
      data: {}
      msg:
        type: string
    type: object
info:
  contact:
    email: support@swagger.io
    name: API Support
    url: http://www.swagger.io/support
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  termsOfService: http://swagger.io/terms/
paths:
  /admin/info/{id}:
    get:
      consumes:
      - application/json
      description: login admin
      parameters:
      - description: id
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: success
          schema:
            allOf:
            - $ref: '#/definitions/response.RespnseStr'
            - properties:
                data:
                  $ref: '#/definitions/domain.Admin'
              type: object
        "401":
          description: unauthorized
          schema:
            allOf:
            - $ref: '#/definitions/response.RespnseStr'
            - properties:
                data:
                  type: object
              type: object
        "500":
          description: system error
          schema:
            allOf:
            - $ref: '#/definitions/response.RespnseStr'
            - properties:
                data:
                  type: object
              type: object
      summary: login admin
      tags:
      - Admin
  /admin/login:
    post:
      consumes:
      - application/json
      description: login admin
      parameters:
      - description: LoginAndRegisterRequest
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/domain.LoginAndRegisterRequest'
      produces:
      - application/json
      responses:
        "200":
          description: success
          schema:
            allOf:
            - $ref: '#/definitions/response.RespnseStr'
            - properties:
                data:
                  $ref: '#/definitions/domain.LoginResponse-domain_Admin'
              type: object
        "401":
          description: unauthorized
          schema:
            allOf:
            - $ref: '#/definitions/response.RespnseStr'
            - properties:
                data:
                  type: object
              type: object
        "500":
          description: system error
          schema:
            allOf:
            - $ref: '#/definitions/response.RespnseStr'
            - properties:
                data:
                  type: object
              type: object
      summary: login admin
      tags:
      - Admin
  /admin/register:
    post:
      consumes:
      - application/json
      description: register admin
      parameters:
      - description: LoginAndRegisterRequest
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/domain.LoginAndRegisterRequest'
      produces:
      - application/json
      responses:
        "200":
          description: success
          schema:
            allOf:
            - $ref: '#/definitions/response.RespnseStr'
            - properties:
                data:
                  $ref: '#/definitions/domain.Admin'
              type: object
        "401":
          description: unauthorized
          schema:
            allOf:
            - $ref: '#/definitions/response.RespnseStr'
            - properties:
                data:
                  type: object
              type: object
        "500":
          description: system error
          schema:
            allOf:
            - $ref: '#/definitions/response.RespnseStr'
            - properties:
                data:
                  type: object
              type: object
      summary: register admin
      tags:
      - Admin
  /user/info/{id}:
    get:
      consumes:
      - application/json
      description: login user
      parameters:
      - description: id
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: success
          schema:
            allOf:
            - $ref: '#/definitions/response.RespnseStr'
            - properties:
                data:
                  $ref: '#/definitions/domain.User'
              type: object
        "401":
          description: unauthorized
          schema:
            allOf:
            - $ref: '#/definitions/response.RespnseStr'
            - properties:
                data:
                  type: object
              type: object
        "500":
          description: system error
          schema:
            allOf:
            - $ref: '#/definitions/response.RespnseStr'
            - properties:
                data:
                  type: object
              type: object
      summary: login user
      tags:
      - User
  /user/login:
    post:
      consumes:
      - application/json
      description: login user
      parameters:
      - description: LoginAndRegisterRequest
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/domain.LoginAndRegisterRequest'
      produces:
      - application/json
      responses:
        "200":
          description: success
          schema:
            allOf:
            - $ref: '#/definitions/response.RespnseStr'
            - properties:
                data:
                  $ref: '#/definitions/domain.LoginResponse-domain_User'
              type: object
        "401":
          description: unauthorized
          schema:
            allOf:
            - $ref: '#/definitions/response.RespnseStr'
            - properties:
                data:
                  type: object
              type: object
        "500":
          description: system error
          schema:
            allOf:
            - $ref: '#/definitions/response.RespnseStr'
            - properties:
                data:
                  type: object
              type: object
      summary: login user
      tags:
      - User
  /user/register:
    post:
      consumes:
      - application/json
      description: register user
      parameters:
      - description: LoginAndRegisterRequest
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/domain.LoginAndRegisterRequest'
      produces:
      - application/json
      responses:
        "200":
          description: success
          schema:
            allOf:
            - $ref: '#/definitions/response.RespnseStr'
            - properties:
                data:
                  $ref: '#/definitions/domain.User'
              type: object
        "401":
          description: unauthorized
          schema:
            allOf:
            - $ref: '#/definitions/response.RespnseStr'
            - properties:
                data:
                  type: object
              type: object
        "500":
          description: system error
          schema:
            allOf:
            - $ref: '#/definitions/response.RespnseStr'
            - properties:
                data:
                  type: object
              type: object
      summary: register user
      tags:
      - User
securityDefinitions:
  Bearer:
    description: Type "Bearer" followed by a space and JWT token.
    in: header
    name: Authorization
    type: apiKey
swagger: "2.0"
